// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:6a547f16-bed9-4d98-bd37-1d9ecfa6dd36",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_DOQe3T3SV",
    "aws_user_pools_web_client_id": "7gf6di3444vo6ahf7e63m873ut",
    "aws_user_files_s3_bucket": "myface264011386d4a41f082e7f6b6c4be9ad3",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
